global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: 'etl-go'
    static_configs:
      - targets: ['etl-go:8080']
    metrics_path: '/metrics'
    scrape_interval: 5s
    scrape_timeout: 5s
